# This file is created by setup.py. See config.yaml for definitions
# of these values. You can modify the values in this file either 
# directly or by re-running setup.py.

external:

local:
  executables:
    python: python
    r: r
    stata: statmp
    matlab: matlab
    lyx: lyx
    latex: latex
