name: template #CHANGE for your project
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pyyaml=6.0
  - numpy=1.21.6
  - matplotlib=3.5.3
  - gitpython=3.1.27 
  - termcolor=1.1.0
  - colorama=0.4.5
  - jupyter=1.0.0
  - linearmodels=4.24
  #  - pendulum
  # - MoviePy
  # - pip=19
  # - pip: # if there is a package available via pip but not with conda, can import like this:
  - r=3.6
  - r-yaml # import r packages by prepending with "r-""
  # - r-nicheROVER
