name: Sync Back to Dev Branch
on:
  push:
    branches:
      - '*_sync'

jobs:
  sync_back:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set globals
      run: |
        echo 'Prueba'
        
    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout code from mirror
      uses: actions/checkout@v2
      with:
        ref: '<master_branch_name>'

    - name: Checkout dev branch
      run: |
        git clone git@github.com:<original_repo_username>/<project_name>.git
        git fetch --unshallow
        cd <project_name>
        git checkout <issue_branch_name>

    - name: Merge and Push
      run: |
        cd <project_name>
        git config pull.rebase false
        git config --global user.email "you@example.com"
        git config --global user.name "Your GitHub Username"
        git pull ../ <master_branch_name>
        git push origin <issue_branch_name>
