name: Sync to Mirror Repository

on:
  push:
    branches:
      - '*'
env:
  REPO_BRANCH: ${{ github.ref }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "Repository Name: $REPO_NAME"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Get branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Get user email
        id: user_email
        run: |
          USERNAME=${GITHUB_ACTOR}
          USER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/user/emails" | jq -r '.[0].email')
          echo "User Email: $USER_EMAIL"
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV

      - name: Checkout mirror repository
        run: |
          git clone git@github.com:${GITHUB_ACTOR}/${REPO_NAME}_${BRANCH_NAME}_sync.git
          cd ${REPO_NAME}_${BRANCH_NAME}_sync
          git fetch --unshallow
          git checkout $BRANCH_NAME

      - name: Merge and Push
        run: |
          cd ${REPO_NAME}_${BRANCH_NAME}_sync
          git config pull.rebase false
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USERNAME"
          git pull origin $BRANCH_NAME
          git push origin $BRANCH_NAME
